language: node_js
node_js:
  - "9"
dist: trusty
#sudo: required
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_script:
  - npm install
  - npm install -g @angular/cli
script:
  - pushd front
  - ng build --prod
  - popd

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ledwallapp
  on:
    branch: master
