language: node_js
node_js:
  - "9"
dist: trusty
#sudo: required
cache:
  directories:
    - front/node_modules
    - back/node_modules
branches:
  only:
  - master
  - /v\d+\.\d+[a-z]/
before_script:
  - npm install -g @angular/cli
script:
  - pushd front
  - npm install
  - ng build --prod
  - zip -r front.zip dist/ledwallapp
  - popd
  - pushd back
  - npm install
  - popd
  - zip -r back.zip back

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "front/dist/front.zip"
    - "back.zip"
  skip_cleanup: true
  on:
    tags: true
