language: node_js
node_js:
  - "9"
dist: trusty
#sudo: required
cache:
  directories:
    - front/node_modules
    - back/node_modules
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - pushd front
  - npm install
  - ng build --prod
  - zip -r front.zip dist/ledwallapp
  - popd
  - pushd back
  - npm install
  - popd
  - zip -r back.zip back
before_deploy:
  - export TRAVIS_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - git config --local user.name "louisthomaspro"
  - git config --local user.email "louisthomas.pro@gmail.com"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - front/dist/front.zip
    - back.zip
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
